### ISSUE TITLE
Pre-Trained Weights

### ISSUE THREAD

**Issue by tomanick** [awjuliani/pytorch-diffusion#3]
Thanks for your contribution.
I am curious about whether there are any pre-trained weights available for Diffusion Models?

Many thanks!

**Comment by awjuliani** [comment]
There are many pretrained text-to-image diffusion models available on Huggingface: https://huggingface.co/models?pipeline_tag=text-to-image&sort=trending

**Comment by tomanick** [comment]
Thanks for your reply.
Could we use the diffusion model architecture of this Github repository to load these pre-trained weights?

**Comment by awjuliani** [comment]
This project is a very simple example of how to implement diffusion. The models available on huggingface are much more complex and usable. I would recommend you take a look at the diffusers library: https://github.com/huggingface/diffusers
